name: Repo Sync NotionNext

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/Repo-Sync-NotionNext.yaml'
  schedule:
    - cron: '38 */4 * * *'

jobs:
  sync-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Force sync with upstream repository
        run: |
          git remote add upstream https://github.com/tangly1024/NotionNext.git
          git fetch upstream main
          git reset --hard upstream/main
          git push origin main --force
