name: Repo Sync NotionNext

on:
  workflow_dispatch:

  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/Repo-Sync-NotionNext.yaml'

  schedule:
    - cron: 38 */4 * * *

jobs:
  sync-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Create repository
        run: |
          repo_exists=$(curl -H "Authorization: token ${{ secrets.ACTION_SECRET }}" \
            https://api.github.com/repos/${{ github.repository_owner }}/NotionNext | jq -r .name)
          if [[ "$repo_exists" != "NotionNext" ]]; then
            curl -X POST -H "Authorization: token ${{ secrets.ACTION_SECRET }}" \
              https://api.github.com/user/repos -d '{"name":"NotionNext"}'
          fi
      - name: Sleep Random Time
        run: sleep $(shuf -i 10-60 -n 1)
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: NotionNext
        run: |
          bash Scripts/Sync.sh \
            https://github.com/tangly1024/NotionNext main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/xmlySpeed/NotionNext main