name: Repo Sync NotionNext

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/Repo-Sync-NotionNext.yaml'
  schedule:
    - cron: '38 */4 * * *'

jobs:
  sync-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: tangly1024/NotionNext
          ref: main

      - name: Force sync to target repository
        run: |
          git remote add target https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/rzrcazk/NotionNext.git
          git push target main --force
